SUBDIR = tex_mc\WinTeX\ 
SRCS =	b_config.mtp bibtex.mtp d_config.mtp install.mtp m_config.mtp \
		makeidx.mtp preview.mtp t_config.mtp virtex.mtp
ITPS = instinfo.itp
!INCLUDE	..\..\makefile.in

all	:	this

clean : clean_this

