SUBDIR = tex_mc\pTeX2GUI\ 
SRCS =	b_config.mtp bibtex.mtp install.mtp m_config.mtp makeidx.mtp \
		t_config.mtp virtex.mtp
ITPS = instinfo.itp
!INCLUDE	..\..\makefile.in

all	:	this

clean : clean_this

