SUBDIR = tex_mc\pTeX2\ 
SRCS =	b_config.mtp bibtex.mtp install.mtp m_config.mtp makeidx.mtp \
		t_config.mtp virtex.mtp update.mtp
ITPS = instinfo.itp fmtname.itp
!INCLUDE	..\..\makefile.in

all	:	this

clean : clean_this

